# Generated by Django 5.1 on 2024-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='Default summary', max_length=130),
            preserve_default=False,
        ),
    ]
